### ISSUE TITLE
Double declaring the bootloader (conflicting)

### ISSUE THREAD

**Issue by brianmcgillion** [tiiuae/ghaf#100]
❯ nix flake show
warning: Git tree '/home/brian/projects/code/github.com/tiiuae/ghaf' is dirty
git+file:///home/brian/projects/code/github.com/tiiuae/ghaf
├───formatter
│   ├───aarch64-linux: package 'alejandra-3.0.0'
│   └───x86_64-linux: package 'alejandra-3.0.0'
├───hydraJobs
│   ├───intel-nuc-debug
│   │   └───x86_64-linux: derivation 'nixos-disk-image'
│   └───nvidia-jetson-orin-debug
│       └───aarch64-linux: derivation 'nixos-disk-image'
├───nixosConfigurations
│   ├───imx8qm-mek-debug: NixOS configuration
│   ├───imx8qm-mek-release: NixOS configuration
│   ├───intel-nuc-debug: NixOS configuration
│   ├───intel-nuc-release: NixOS configuration
│   ├───netvm-imx8qm-mek-debug: NixOS configuration
│   ├───netvm-imx8qm-mek-release: NixOS configuration
│   ├───netvm-intel-nuc-debug: NixOS configuration
│   ├───netvm-intel-nuc-release: NixOS configuration
│   ├───netvm-nvidia-jetson-orin-debug: NixOS configuration
│   ├───netvm-nvidia-jetson-orin-release: NixOS configuration
│   ├───netvm-vm-debug: NixOS configuration
│   ├───netvm-vm-release: NixOS configuration
│   ├───nvidia-jetson-orin-debug: NixOS configuration
│   ├───nvidia-jetson-orin-debug-from-x86_64: NixOS configuration
│   ├───nvidia-jetson-orin-release: NixOS configuration
│   ├───nvidia-jetson-orin-release-from-x86_64: NixOS configuration
│   ├───vm-debug: NixOS configuration
│   └───vm-release: NixOS configuration
└───packages
    ├───aarch64-linux
    │   ├───doc: package 'ghaf-doc'
error: The option `boot.loader.grub.enable' has conflicting definition values:
       - In `/nix/store/lzv828iaf3p4kjhdsj1vgfn4n510a94x-source/nxp/common/modules.nix': true
       - In `/nix/store/5592s3m0cf14nmqm2g14f6mz6plqb9f7-source/nixos/modules/system/boot/loader/systemd-boot/systemd-boot.nix': false
(use '--show-trace' to show detailed location information)

This is caused by the modules/host/minimal.nix declaring systemd boot, while the imx8 is declaring grub.

**Comment by mikatammi** [comment]
https://github.com/tiiuae/ghaf/pull/99 I just created a PR to fix this one hour ago, but I guess I can close it
