### ISSUE TITLE
installer: sensible, user-friendly timeout with prompt to remove installation media before booting into the installed system

### ISSUE THREAD

**Issue by vilvo** [tiiuae/ghaf#286]
I tested the installer and there are some rough edges, for example I was staring away from laptop while it was installing, then it rebooted, and I wasn't fast enough to disconnect the USB-drive. So the system somehow strangely booted up into ghaf desktop but still something was mounted from USB-drive.

But I'm fine with merging this now and improving things later.

_Originally posted by @mikatammi in https://github.com/tiiuae/ghaf/issues/249#issuecomment-1739114493_

**Comment by brianmcgillion** [comment]
Has been fixed. there is a prompt now asking the user to reboot and notifying to remove the install media
