### ISSUE TITLE
Link to the archived repository #2

### ISSUE THREAD

**Issue by jenninikko** [tiiuae/ghaf#35]
On this page https://tiiuae.github.io/ghaf/build_config/build_configurations.html:
_If you want to try and check the details, see the [build-configurations](https://github.com/tiiuae/build-configurations/) repository._

Since this repository is now archived, how can we try and verify it now?

Will this instruction be enough? https://github.com/tiiuae/ghaf#build-instructions

**Comment by vilvo** [comment]
Fixed with https://github.com/tiiuae/ghaf/commit/bdf4d5216708f314be34eb0129aaaa825144edb4#diff-87438aacd4f16c2349fe4a4fe54603d4ef6a95098d92d8c1fed5f9ac01119f15R5
