### ISSUE TITLE
Find and Replace all occurrences of IFD in Ghaf

### ISSUE THREAD

**Issue by brianmcgillion** [tiiuae/ghaf#372]
https://nixos.org/manual/nix/unstable/language/import-from-derivation

This causes slow evaluation times as packages have to be realised along the way. It can also constitute final images being built numerous times making e.g. `nix flake check` and `nix-fast-build` take inordinate amounts of time and in part is leading to the OOM that is encountered when running these on standard hardware.

Currently, nix flake check only succeeds in the following situation `nix flake check --allow-import-from-derivation` as flakes generally disallow IFD in their evaluation.

**Comment by henrirosten** [comment]
Worth mentioning that `nix flake check --allow-import-from-derivation` on Ghaf currently requires aarch64-linux remote builder, otherwise, it fails as follows:

```
$ nix flake check --allow-import-from-derivation
error:
       … while checking flake output 'packages'

         at «none»:0: (source not available)

       … while checking the derivation 'packages.x86_64-linux.nvidia-jetson-orin-agx-release-flash-script'

         at «none»:0: (source not available)

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: a 'aarch64-linux' with features {} is required to build '/nix/store/6gfd6yn7a6fl2ywqg29vvybrp8kbaxrg-boot.json.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test, uid-range}
```

**Comment by mikatammi** [comment]
This is fixed, as plain `nix flake check` without `--allow-import-from-derivation` works now.
