### ISSUE TITLE
nix flake check: OOM

### ISSUE THREAD

**Issue by henrirosten** [tiiuae/ghaf#385]
`nix flake check` runs out of memory even after https://github.com/tiiuae/ghaf/issues/372.

Following reproduction steps were run on x86_64-linux with 16-cores and 32GB memory (no remote builder is configured):

Git HEAD:
```
$ git log -1 --pretty=oneline
8f8f6538807f8afd9f08dc6a162c5f407f69bc5b (HEAD -> main, origin/main, origin/HEAD) Fix reuse compliance
```
Run `nix flake check` to repro OOM:
```
$ nix flake check
checking flake output 'checks'Killed
```
Verify from `journactl` that it's killed due to OOM:
```
$ journalctl | tail -n500 | grep -i "Out of memory"
Dec 01 09:35:07 duamix kernel: Out of memory: Killed process 1808882 (nix) total-vm:27647872kB, anon-rss:27439060kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:53844kB oom_score_adj:0
```

**Comment by brianmcgillion** [comment]
I do not believe that we can fix this `nix flake check` we can use [nix-eval-jobs](https://github.com/nix-community/nix-eval-jobs), though defining a generic num-jobs and max-memory might not be generic enough. Can try to add it as an option to the `nix develop` environment.

**Comment by brianmcgillion** [comment]
make-checks merged to mainline and now included in GH actions checks section
