### ISSUE TITLE
Point to Ghaf SBOM page in scs.html

### ISSUE THREAD

**Issue by ktusawrk** [tiiuae/ghaf#48]
In the page https://tiiuae.github.io/ghaf/scs/scs.html
in the second paragraph under the illustration, there is a link
- Link text: software bill of materials (SBOM)
- Link URL: https://fossa.com/blog/software-bill-of-materials-formats-use-cases-tools/

Now that we have a dedicated Software Bill of Materials page in Ghaf GitHub pages, we should be pointing to it
-> Replace link URL with: https://tiiuae.github.io/ghaf/scs/sbom.html  

**Note**: in https://tiiuae.github.io/ghaf/scs/sbom.html there is a link also to Fossa page so no information is lost.

**Comment by jenninikko** [comment]
I added the term to the glossary https://github.com/tiiuae/ghaf/pull/72
