### ISSUE TITLE
Fix link to NixOS site

### ISSUE THREAD

**Issue by ktusawrk** [tiiuae/ghaf#9]
In the page https://tiiuae.github.io/ghaf/build_configurations.html
There is a sentence "The canonical URL for the upstream git repository is: https://github.com/NixOS."

Currently the "https://github.com/NixOS" is not clickable, i.e. does not work as a link.

@jenninikko

**Comment by jenninikko** [comment]
Fixed with https://github.com/tiiuae/ghaf/pull/20.
